### ISSUE TITLE
[Feature Request] Tag tasks

### ISSUE THREAD

**Issue by muguu** [WetHat/OnenoteTaggingKit#10]
I'd like to do Task management with OneNote, but it only allows assigning tasks to a person via Outlook.
With a "Tag tasks" plugin, which adds person-tags to a task, it could be possible to display all tasks for a specific person-tag.

In addition, If a note is created via Outlook or Skype, the participants could be shown as person-tags already within the Tag-Task Plugin.

What do you think?

**Comment by muguu** [comment]
The reason why I abandoned OneNote years ago and started working with ZimWiki is because of the inconvenient way of handling tags.

So to give you more details on my use case:

![image](https://user-images.githubusercontent.com/3179431/41351140-be155c98-6f15-11e8-82ee-5ebf2babb0b5.png)

Search gives back:

![image](https://user-images.githubusercontent.com/3179431/41351166-dc9c3b96-6f15-11e8-8a69-f5e771150c68.png)


So technically, I wouldn't differentiate between normal tags and person tags. But I don't want to create a category for each tag I want to use as a person tag. In other words: Would it be possible to add a tag into a text which is set as a task?

Thank you and Regards,
Muguu

**Comment by WetHat** [comment]
Hi muguu,

I think I understand your usecase. Technically it is possible to programmatically add tags anywhere on a page. The difficulty is more on the side of tag management. Tags managed by the tagging kit are managed in the page metadata (unlike genuine OneNote tags). A particular tag can appear only once on a page. If we would allow putting tags anywhere on a page this uniqueness criterion would no longer be feasible and we would need to manage multiple instances of a tag. Also since the tag is now visible, it could be deleted by the user outside of the tagging kit. Unfortunately OneNote events, such as the edit page event, are not passed through to the add-in (a generic limitation of .net add-ins) so we would loose track of those tags. Currently I see no way to make this work reliably. I need to think a bit more about this.

WetHat

**Comment by muguu** [comment]
Hi WetHat,

>A particular tag can appear only once on a page. If we would allow putting tags anywhere on a page this uniqueness criterion would no longer be feasible and we would need to manage multiple instances of a tag

Well, a tag helps you find the page. The same tag within a page could be seen as 'anchor tags' to find specific chapters within a page to which the tag refers to.

>The difficulty is more on the side of tag management. Tags managed by the tagging kit are managed in the page metadata (unlike genuine OneNote tags). 

Are you able to create OnteNote tags programmatically?

>Unfortunately OneNote events, such as the edit page event, are not passed through to the add-in (a generic limitation of .net add-ins) so we would loose track of those tags. 

I see your point. ZimWiki is much more communicative on events towards plugins.

>Also since the tag is now visible, it could be deleted by the user outside of the tagging kit. 

Are the tags your plugin adds on a page supposed to be un-deletable? I can click the box and delete the plugin text...

**Comment by WetHat** [comment]
Hi muguu,

> The same tag within a page could be seen as 'anchor tags' to find specific chapters within a page to which the tag refers to.
Yes, I agree that is how I would imagine this use-case too.

> Are you able to create OnteNote tags programmatically?

Yes. However, tags on the page would be paragraph tags (the only kind of tags OneNote supports).   Supposed we could find a good way to manage tags in the OneNote page content, it still would still look like this:
<br/>
![image](https://user-images.githubusercontent.com/10697674/41707707-10bcab2a-753f-11e8-8722-05b21151a89f.png)
<br/>
Tags embedded in the paragraph text like so:
<br/>
![image](https://user-images.githubusercontent.com/10697674/41707112-b02a5dc6-753d-11e8-81b7-9c899cf386c1.png)
<br/>
are not possible in OneNote. This implies we would need a different approach such as:<br/>
-  inserting a special unicode character to mark the _person_ tag:<br/>
   ![image](https://user-images.githubusercontent.com/10697674/41707656-eec40d10-753e-11e8-9a0d-42aae63d336c.png)<br/>
- Just the person's email:<br/>
  ![image](https://user-images.githubusercontent.com/10697674/41707969-a7e58454-753f-11e8-97fe-e3b682044d53.png)<br/>

In either case we would need to _scan_ the page for these tags, as edit events are not available. These tags would be then treated as page tags. The scanning process could be used to detect other types of tags too, like mebedded hashtags. The down side is that manual edits to the tags would be unnoticed until the page is scanned for tags again.

> Are the tags your plugin adds on a page supposed to be un-deletable? I can click the box and delete the plugin text...
Yes. However, OneNote does not allow read-only paragraphs. Any manual edits to the tag box are not reflected in the search result. When you you use the _Tag Pages_ dialog on that page again the user edits discarded and the initial tags re-appear. This is because tags are actually stored in the page metadata. The tag box is just a visualization.

WetHat

**Comment by muguu** [comment]
>>The difficulty is more on the side of tag management. Tags managed by the tagging kit are managed in the page metadata (unlike genuine OneNote tags).

>Are you able to create OnteNote tags programmatically?

I did some research and found out that there is no way to create build in tags :(

I played around with the Onetastic Makros and was thinking if following idea could be implementable within your plugin?

![image](https://user-images.githubusercontent.com/3179431/41716680-8b11ea62-7557-11e8-9397-7e45f253deb1.png)


What if there would be an additional option within  "find tagged pages", in which I can search for a built in tag together with the full text search against a context tag?


![image](https://user-images.githubusercontent.com/3179431/41716659-77dbad0c-7557-11e8-890a-71affe27feb9.png)



Additionally, you could also parse against a date (something like >2018-06-21 and <2018-06-30 with > as a start date and < as a due date). With an additional filtering option against a date, you could then display tasks which are already due etc...

What do you think?

Regards,
Muguu

**Comment by WetHat** [comment]
Hi @muguu ,

You can now add person tags to tasks manually. With [feature release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.8.7617) it is possible to map hashtags and _classic_ OneNote tags to page tags. Given the limits of the OneNote API this is as close as it gets  to your use case.
