### ISSUE TITLE
copy links to pages not works as well

### ISSUE THREAD

**Issue by zhongguocn** [WetHat/OnenoteTaggingKit#17]
When I use Find Tagged Pages,  There are more than 10 pages in Fonud Pages.
Select All,  then click "copy links to pages"

paste in a new page,  only a part of them are pasted,  the others are missing

Can you fix this error?
thanks a lot

**Comment by WetHat** [comment]
Turns out that this was actually a timing issue. Creating links for a large selection of pages OneNote takes a long time. Chances are that you go ahead and try to paste before the links were created. To address this I've added a progress bar to the search dialog, so that you would know when the links are ready to paste.

WetHat

**Comment by zhongguocn** [comment]
Thanks.

I find 71 pages,  click "copy links to pages",
10 minutes after that
paste in a new page, only 47 links are pasted, the others are missing

copy links and paste in 1 seconds
only 47 links are pasted, the others are missing

10 minutes or 1 seconds, same result

**Comment by WetHat** [comment]
I think your selection contains pages which are already in the OneNote Recycle Bin. Links to pages in the Recycle Bin are **not** generated. Could you please check that the missing links are related to pages in the Recycle Bin.

Thanks,

WetHat
