### ISSUE TITLE
Adding existing tags to page with keyboard (Suggested Tags)

### ISSUE THREAD

**Issue by muguu** [WetHat/OnenoteTaggingKit#22]
**My use case:**
When I want to add a tag to a page with the "Tag Pages" dialogue, I usually start typing a tag instead of trying to find if the tags exists within the "Suggested Tags".

As the list of "Suggested Tags" is reduced to the matches of what I typed, I quickly see if the tag already exists.

I continue typing the tag until there is either only one suggested tag left, or I complete typing the tag as it is a new tag.

So far so good.

With the new keyboard shortcut (issue [https://github.com/WetHat/OnenoteTaggingKit/issues/9](url)), I can now quickly add this tag to the page without the need to grab the mouse and click on the add tags (green plus) (Thanks a lot for adding this).

**My issue:**
However, if I want to add an existing tag, and I keep typing until one tag is left within the "Suggested Tags", I can't stop typing and press Enter or SHIFT+Enter or CTRL++ as the uncompleted tag would be added to the tags list.

**Workaround:**
I could cycle the focus to the remaining suggested tag with TAB and then press Enter, but SHIFT+Enter does not work here.

**My suggestion:**
Preferred:
If there is only one tag left, prefill this into the Input Dialogue like this:
![image](https://user-images.githubusercontent.com/3179431/58313815-b7cfc680-7e0e-11e9-93f8-250bd677c230.png)

Assuming that I typed "OneNote" and only OneNoteTagging is the only remaining existing tag.

If "OneNote" is the tag I want to add, I press DEL first to reject the autocompletion and press SHIFT + Enter or CTRL ++
If "OnteNoteTagging" is the tag I want to add, I press SHIFT+Enter or CTRL ++
If OneNoteisGreat is the tag I want to add, I continue typing and the autocompletion is removed.

Possible other but less intuitive implementation:
Add possibility to use SHIFT+Enter or CTRL++ if I switch the focus to a tag with TAB

Thanks in Advance
Muguu

**Comment by WetHat** [comment]
Hi muguu,
I've experimented with auto-complete if just one tag is selected, but found it annoying when you actually want to create a new tag which happens to be a substring of an existing tag. Therefore I settled with enabling keyboard input in the _Suggested Tags panel_ so that in addition to
'ENTER' the special keys described in: [Tagging a Page](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-a-Page) would work as well.

The first release including this change would be [3.6](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.6).

Hope you can live with this,

WetHat

**Comment by WetHat** [comment]
@all-contributors add @muguu for ideas
