### ISSUE TITLE
installation issue ? 

### ISSUE THREAD

**Issue by Delli** [WetHat/OnenoteTaggingKit#25]
let me start to emphasize that i did to much changes at once
not sure what happened exactly! sorry

I  installed without errors. the addin seems to work .
only the search looks broken ? my search is slow windows services gives 
![SearchIndexOptions](https://user-images.githubusercontent.com/4728038/74590631-6573ad00-5010-11ea-94ab-a860b1eb1069.png)

looks like windows service  is not picking up the right one note location is this correct? 

Can there be a connection with the OnenoteTaggingKit installer ? 
if not can you reference me to some docs concerning this issue ? (looks like regedit micro surgery ) 

side issue : 
i am newbie when working with tags and faceted search.
My hope is to find a better balance with maintenance of my notes and mis en hit ratio in searching to find a note i know must exist.
Still contemplating if this is more a psychological issue than a technical but anyways your taggingkit has giving me hope i can make it a technical. Anyways thank you for that. Are there any best practices or articles you would advice?

thanks in advance

**Comment by WetHat** [comment]
Hi Delli,

> _Can there be a connection with the OnenoteTaggingKit installer ?_

Most likely not. The installer does not change any Windows search settings. It just registers the add-in with OneNote.

> _the addin seems to work .only the search looks broken_

What exactly does that mean? I suppose you refer to the search dialog in the tagging kit extension not the genuine OneNote search. Does it display to few or wrong results? You may also  want to check out this issue [Searching pages by Tags or Full Text Queries does not work](https://github.com/WetHat/OnenoteTaggingKit/wiki/Searching-pages-by-Tags-or-Full-Text-Queries-does-not-work). There was once a problem in one of the Microsoft Office 32-bit versions with OneNote search as described in [OneNote 2016 Integration with Windows Search Service broken after Windows 10 Creators update](https://social.msdn.microsoft.com/Forums/en-US/da9e57fd-be10-4d5c-a088-62acd9d8880a/onenote-2016-integration-with-windows-search-service-broken-after-windows-10-creators-update). That issue has been fixed by Microsoft by now. So the question would be what version of Windows and OneNote are you using?

> _Are there any best practices or articles you would advice?_

[A Digital Editor’s Guide to Content Tagging](https://www.paceco.com/insights/design-development/digital-editors-guide-to-content-tagging/) has some good tips concerning tagging.

WetHat

**Comment by WetHat** [comment]
Without more specific information there is nothing I can do. I have to resolve this as  'not reproducible'

**Comment by zhongguocn** [comment]
There’s no plug-in menu in onenote’s menu bar.I can’t find error prompt or code.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Peter Ernst <notifications@github.com>
发送时间: Thursday, March 26, 2020 5:26:17 PM
收件人: WetHat/OnenoteTaggingKit <OnenoteTaggingKit@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [WetHat/OnenoteTaggingKit] installation issue ? (#25)


Closed #25<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWetHat%2FOnenoteTaggingKit%2Fissues%2F25&data=02%7C01%7C%7Cb71a49ff22364ce3ed6808d7d167bd5b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637208115790173594&sdata=p2OlmvjGpTarSP4YgU5%2B%2FjSdtJrWTSge6DKCiFn7B3E%3D&reserved=0>.

―
