### ISSUE TITLE
Ability to tag individual paragraphs with tags written into the notes

### ISSUE THREAD

**Issue by Spectrem12** [WetHat/OnenoteTaggingKit#29]
Example:

Provide links to code repos to #bob on #python scripts

**Comment by WetHat** [comment]
Hi @Spectrem12,

Tagging and linking to individual paragraphs with hashtags via the addin  would destrastically impact performance, because:
* The tagging relies on the Onenote search infrastructure
* the OneNote search infrastructure does not understand hashtags.
* page text would need to be scanned for hashtags (rather than using the search service).

However I can imagine following approach:

1 Extend the `Tag Pages -> `Presets` -> `Tags From Current Page` action to search for hashtags in the page text
2. Promote the hashtags found in the page text to regular page tags

I also would suggest to make this feature optional (configurable).

**Advantages**

* This allows the hashtags to take part in facetted search. 
* Same performance as page tags
* Minor use model change only

**Disadvantages**

* If hashtags are added/deleted from page text, the `Presets` -> `Tags From Current Page` needs to ve (re-)executed manually to update the page tags.

What do you think?

**Comment by WetHat** [comment]
Using a similar approach as described in #35. The hashtags found in the page text are promoted to page tags and can participate in facetted search.

**Comment by WetHat** [comment]
Fixed in this [feature release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.8.7617)
