### ISSUE TITLE
TAGS bug in note and required change in UI 

### ISSUE THREAD

**Issue by Raquo116** [WetHat/OnenoteTaggingKit#34]
After adding a tag, if we delete the tag appeared in the note by using backspace or simply cut it, the tags remain for that particular page if we use the "find pages"/search tag option.

It would be better if we implement the EVERNOTE STYLE tags mention in pages.
![tags](https://user-images.githubusercontent.com/13005473/95911887-ad291f00-0dbf-11eb-8efb-7859fce35eb3.jpg)

**Comment by WetHat** [comment]
Hi @Raquo116,

In the default tag display mode _Below Page Title_ (seems to be one you are using) tags are represented as plain text. This text should be actually read-only because are not the actual tags. but a _display representation_ of the tags only. The actual tags are kept in the page metadata which is invisible. Deleting the text representation does not delete the tag. This behavior reflects the limited capabilitues of the OneNote API. However, if you use the _Icon in Page Title _ display mode this issue goes away. To turn on this mode please refer to the documentation of the [Preferences Tab](https://github.com/WetHat/OnenoteTaggingKit/wiki/Preferences-Tab) which is part of the _Settings_ dialog.

The '_Icon in Page Title ' is also the closest approximation we can get with respect to the _Evernote_ user interface. The OneNote API again does not support an integration which looks like the _Evernote_ user interface.

**Comment by WetHat** [comment]
The inadvertent editing of page tags can now be reverted with this [feature release](https://github.com/WetHat/OnenoteTaggingKit/releases/tag/v3.8.7617). Documentation how to do that is at the bottom of: [Tagging a Page](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-a-Page) .
