### ISSUE TITLE
Any plans on releasing the add-in documentation?

### ISSUE THREAD

**Issue by TheCarsino** [WetHat/OnenoteTaggingKit#61]
I've been trying to customize a version of OneNoteTaggingKit, but there are many properties, classes or methods that I have no idea on how to use them. 

Also, I would want to Debug or Compile the project so I can know where my errors are, but I dont know where can I start.

**Is it planned to develop a new version of the project documentation? If not, how can I test the .dll library?**

Edit-1: I've managed to Debug by using the log files that are implemented, but it only shows the log. Thanks for that.

--

Thanks

**Comment by WetHat** [comment]
Hi @TheCarsino,

_Is it planned to develop a new version of the project documentation?_

The code documentation of the latest release has been updated recently. You can get it [here](https://github.com/WetHat/OnenoteTaggingKit/blob/master/TaggingKitSandcastle/Documentation/Home.md).

There is some rudimentary information on how to setup a dev environment
[here](https://wethat.github.io/OnenoteTaggingKit/v4.0/Home.html#tagging-kit-development).

There isn't any design documentation yet. If time permits, I'll add some in the future. A good point to start  is at the classes in top level source directory. Next you might want  to look at the `common` subdirectory. It contains common UI controls and their support classes.

WetHat

**Comment by TheCarsino** [comment]
> Hi @TheCarsino,
> 
> _Is it planned to develop a new version of the project documentation?_
> 
> The code documentation of the latest release has been updated recently. You can get it [here](https://github.com/WetHat/OnenoteTaggingKit/blob/master/TaggingKitSandcastle/Documentation/Home.md).
> 
> There is some rudimentary information on how to setup a dev environment [here](https://wethat.github.io/OnenoteTaggingKit/v4.0/Home.html#tagging-kit-development).
> 
> There isn't any design documentation yet. If time permits, I'll add some in the future. A good point to start is at the classes in top level source directory. Next you might want to look at the `common` subdirectory. It contains common UI controls and their support classes.
> 
> WetHat

Thank you for updating the code documentation. It really helps a lot.

Also, another question, this one is a little bit personal. Is there a way to debug the program? The log files are useful, but I'll be useful to know the states and values of variables.

**Comment by WetHat** [comment]
Hi @TheCarsino,
_Is there a way to debug the program?_

Sure there is. Assuming you have Visual Studion 2019. Since the _Tagging Kit_ is an _add-in_ it cannot be started directly, but you can **attach** the debugger once the add-in has been loaded.

1. Run Vs2019 _as Administrator_ and load the _OneNoteTagginKit_ solution or project file.
    Though admin mode is not required for debugging it is good practise when working
    with the _Tagging Kit_. As soon as you start building the _Tagging Kit_ project, admin rights are required
    to register the add-in as COM component with the system..
2.  Run OneNote and make sure the add-in is loaded.
3. Open the _Tagging Kit_ `Manage Settings` dialog. This will help you to identify the process to attach the
    debugger to.
4. In VisualStudio execute the `Debug->Attach To Process` action. This opens the `Attach to Process` dialog.
5. Scroll down to the `dllhost` processes and attach the debugger to the one whose title is `Manage Settings`.

Happy debugging,
WetHat
