### ISSUE TITLE
[Feature Request] Provide a keyboard shortcut to tag pages

### ISSUE THREAD

**Issue by muguu** [WetHat/OnenoteTaggingKit#9]
Please provide a keyboard shortcut to open the Tag pages window.
Also would be helpful to allow adding tags to the page by e.g. SHIFT+ENTER within the Tag Pages Window.

This would increase the speed for tagging a page.

**Comment by WetHat** [comment]
Hi Muguu,

Thanks for your feature request. Default key
board shortcuts to open that _Tag Pages_ dialog are already in place. See attached screenshot
![KBD Shortcut](https://user-images.githubusercontent.com/10697674/41145310-f9807052-6aff-11e8-837d-b661ac9aa4f0.png)

In the above exampe the Keyboard shortcut is ALT+H Y1
** Notes**:
* You have the release the ALT key after pressing **H**
* Since these are defaults, the actual shortcuts may be different on your system.

I'll see if I can  replace the default shortcuts with better ones in the next release. However, all the good letters are already taken.

As for  SHIFT+ENTER: There are three ways to add tags add (**+**), set-to (**=**), remove (**-**).
I suggest to make SHIFT+ENTER configurable, so It can be bound to any of these three actions.

WetHat

**Comment by muguu** [comment]
Hi @WetHat ,

Thanks a lot for your detailed information.
To be honest I find the default keyboard shortcuts quite inconvenient. 

> I'll see if I can replace the default shortcuts with better ones in the next release. However, all the good letters are already taken.

ALT GR + T  seems to be available.

>As for SHIFT+ENTER: There are three ways to add tags add (+), set-to (=), remove (-).

When I open the "Tag Pages" dialog, I can directly type a tag, which is great.
The suggested Tags are instantly filtered against what I type. Which is really great.
I can cycle through the suggested tags with TAB, which is perfect.
I can select with SPACE or RETURN, which is exactly what I expect.

The only missing part here to complete my selection of tags without the use of the mouse is a way to add the selected tags to the page via keyboard.

I suggest:
SHIFT + ENTER  for adding tags (+)
CTRL + (+) for adding tags (+)
CTRL + (=) for set-to (=)
CTRL + (-) for remove (-)

Thank you!

**Comment by WetHat** [comment]
Programmatically or even manually changing OneNote keyboard shortcuts is no longer possible. Hence the only improvements that could be made was to add keyboard short cuts to the _Page Tags_ dialog. Please see [Tagging a Page](https://github.com/WetHat/OnenoteTaggingKit/wiki/Tagging-a-Page) for details.

WetHat

**Comment by medouneu** [comment]
I had a similar question, but also found a solution, at least for OneNote 2016: the Quick Access Toolbar (QAT). I've rarely used it before today, but that might change now.

Short answer, add the OneNote Tagging Kit commands (for Tag Pages and Find) to the QAT, then move those commands to the top, which will assign Alt-1 and Alt-2 as shortcuts to those two commands. Note that unlike most Alt commands, you can hold Alt while pressing the number (or you can press them in succession), which I find is faster.

**Detailed Instructions**

1. Click File --> Options
2. Choose the Quick Access Toolbar tab
3. Check the "Show QAT..." box if it isn't already
4. Set the "Choose commands from" field to "Home Tab"
5. In the left-hand panel, click the "Add tags to or remove tags from..." command
6. Click Add 
7. In the left-hand panel, click the "Find Pages By Tags and Content" command
8. Click Add
9. Next to the right-hand panel, use the arrows to move those two commands to the top of the list (or wherever suits your needs).
10. Click OK
